# Generated by Django 2.2 on 2019-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
