# Generated by Django 2.2 on 2019-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190424_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='readState',
        ),
        migrations.AddField(
            model_name='comment',
            name='from_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Waiting for response', 'Waiting for response'), ('Answered', 'Answered'), ('Close', 'Close')], default='Waiting for response', max_length=20),
        ),
    ]
