# Generated by Django 2.2 on 2019-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190425_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='read',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Waiting for response', 'Waiting for response'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Waiting for response', max_length=20),
        ),
    ]
