# Generated by Django 2.2 on 2019-04-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190429_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attach',
        ),
    ]
